## Here I´m documenting some exercises using the book _Python DataScience HandBook_, will start from the second chapter.

# **Chapter 2: Introduction to NumPy**

In [1]:
import numpy as np

In [ ]:
x = 1000

In [ ]:
# Creating arrays from python lists:

np.array([1,2,3,4,5,6])

np.array([1,2.3,4,5,6])

np.array(['a',2,3])

# All values inside a numpy array have the same type, if not it will try to upcats them

array(['a', '2', '3'], dtype='<U21')

In [ ]:
np.full((3,5), r.randint(1,9))

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [ ]:
np.zeros((2,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
x = np.arange(0,10,2.5)
x

array([0. , 2.5, 5. , 7.5])

In [ ]:
x[::2]

array([0., 5.])

In [ ]:
%timeit 3*3

5.31 ns ± 0.412 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [ ]:
%run "/content/drive/MyDrive/test_script.py"

1 squared is 1
2 squared is 4
3 squared is 9


In [ ]:
!ls /content/drive/MyDrive/Datasets

'AdventureWorks Sales.gsheet'	 FY18_4050_FMRs.csv
 bike_share.csv			 insurance_premiums.csv
 college_datav3.csv		 schoolimprovement2010grants.csv
 daily_show_guests_cleaned.csv


In [ ]:
# Reshaping Arrays

grid = np.arange(1,10).reshape((3,3))
grid


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x = np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [ ]:
horizontal = x[np.newaxis,:]
vertical = x[:,np.newaxis]

print(horizontal, "\n",vertical)

[[1 2 3]] 
 [[1]
 [2]
 [3]]


In [ ]:
# Concatenation

y = np.arange(1,4)

z = np.concatenate([x,y])

z

array([1, 2, 3, 1, 2, 3])

### NumPy Universal Functions

Computation on NumPy arrays can be very fast, or it can be very slow. The key to
making it fast is to use vectorized operations, generally implemented through Num‐
Py’s universal functions (ufuncs)

In [ ]:
# To have fastest results, we applied vectorized ufuncs, it´s applied to each entry

x= np.arange(4)

print(x + 5)
print(x - 5)
print(x * 2)
print(x / 2)
print(x // 2)
print(-x)
print(x ** 2)
print(x % 2)

[5 6 7 8]
[-5 -4 -3 -2]
[0 2 4 6]
[0.  0.5 1.  1.5]
[0 0 1 1]
[ 0 -1 -2 -3]
[0 1 4 9]
[0 1 0 1]


In [ ]:
big_array = np.random.randint(1,1000, size = 1000_000)
big_array

array([262, 332, 460, ..., 126, 643, 940], shape=(1000000,), dtype=int32)

In [ ]:
%timeit (1.0 / big_array)

2.46 ms ± 165 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
1.0 / big_array

array([0.00381679, 0.00301205, 0.00217391, ..., 0.00793651, 0.00155521,
       0.00106383], shape=(1000000,))

In [ ]:
second_big_array = np.random.randint(1,200, size = 1000_000)
second_big_array

array([ 32,  91, 181, ..., 150, 119,  34], shape=(1000000,), dtype=int32)

In [ ]:
%timeit (second_big_array / big_array)

2.9 ms ± 4.06 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%timeit np.divide(second_big_array,big_array)

3.26 ms ± 20.7 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# **Chapter 3: Data Manipulation with Pandas**

In [4]:
import pandas as pd
import numpy as np

In [5]:
pd.__version__

'2.2.2'

## Introducing Pandas Objects

1. The Pandas Series Object

In [ ]:
data = pd.Series([0.25,0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [ ]:
np_arr = np.array([0.25,0.5,0.75,1.0])
np_arr

array([0.25, 0.5 , 0.75, 1.  ])

In [ ]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [ ]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
print(data[0])
print(data[:3])

0.25
0    0.25
1    0.50
2    0.75
dtype: float64


In [ ]:
# Using alternative indexing

data = pd.Series(
    [0.25,0.5,0.75,1.0],
    index = ['a','b','c','d']
)
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [ ]:
data['b']

np.float64(0.5)

In [ ]:
# Series as specialized dictionary

population = {
    'California': 38332521,
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 195528
}
pop_series = pd.Series(population)
pop_series

California    38332521
Texas         26448193
New York      19651127
Florida         195528
dtype: int64

In [ ]:
for i in pop_series:
    print(i)

38332521
26448193
19651127
195528


In [ ]:
pop_series['California':'New York']

California    38332521
Texas         26448193
New York      19651127
dtype: int64

In [ ]:
# Construction Series Objects

pd.Series(5, index = [100,200,300])

100    5
200    5
300    5
dtype: int64

In [ ]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

2. The Pandas DataFrame Object

In [ ]:
area_dict = {
    'California': 423967,
    'Texas': 695662,
    'New York': 141297,
    'Florida': 170312,
}

area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
dtype: int64

In [ ]:
states = pd.DataFrame({
    'population': pop_series,
    'area': area
})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida         195528  170312

In [ ]:
states.index

Index(['California', 'Texas', 'New York', 'Florida'], dtype='object')

In [ ]:
df = states.reset_index().rename(columns={'index':'state'}).copy()
df

state  population    area
0  California    38332521  423967
1       Texas    26448193  695662
2    New York    19651127  141297
3     Florida      195528  170312

In [ ]:
states.columns

Index(['population', 'area'], dtype='object')

In [ ]:
# Constructing DataFrame objects

# From a single Series object

pd.DataFrame(
    data = pop_series,
    columns = ['population']
)

population
California    38332521
Texas         26448193
New York      19651127
Florida         195528

In [ ]:
# From a list of dicts

data = [{'a':i+1, 'b': 2 * (i+1)} for i in range(3)]

pd.DataFrame(data)

a  b
0  1  2
1  2  4
2  3  6

In [ ]:
# From a two-dimensional NumPy array

pd.DataFrame(
    data = np.random.randint(10, size = (3,2)),
    columns = ['foo', 'bar'],
    index = ['a','b','c']
)

foo  bar
a    0    9
b    3    6
c    9    2

In [ ]:
# From a NumPy structured array

A = np.zeros(
    3,
    dtype = [('A', 'i8'), ('B', 'f8')]
)
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [ ]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

3. The Pandas Index Object

In [6]:
ind = pd.Index([2,3,5,7,11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [ ]:
# Index as immutable array

ind[1]

np.int64(3)

In [ ]:
ind[::2]

Index([2, 5, 11], dtype='int64')

In [7]:
# Different from ap arrays, pd Indexes are not mutable, will prove it with the next example

ind[1] = 56

TypeError: Index does not support mutable operations

In [ ]:
# Index as ordered set

indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])

In [ ]:
indA.intersection(indB) # intersection

Index([3, 5, 7], dtype='int64')

In [ ]:
indA.union(indB)  # union

Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [ ]:
indA.symmetric_difference(indB) # symmetric difference

Index([1, 2, 9, 11], dtype='int64')

## Data Indexing and Selection

1. Data Selection in Series

In [ ]:
data = pd.Series(
    [0.25,0.5,0.75,1],
    index = ['a','b','c','d']
)
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [ ]:
'a' in data

True

In [ ]:
# Series as one-dimensional array

# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [ ]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [ ]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [ ]:
# fancy indexing
data[['a', 'd']]

a    0.25
d    1.00
dtype: float64

Indexers: loc, iloc, and ix

These slicing and indexing conventions can be a source of confusion. For example, if
your Series has an explicit integer index, an indexing operation such as data[1] will
use the explicit indices, while a slicing operation like data[1:3] will use the implicit
Python-style index.

In [ ]:
data = pd.Series(
    ['a','b','c'],
    index = [1,3,5]
)
data

1    a
3    b
5    c
dtype: object

In [ ]:
data[1]

'a'

In [ ]:
data[1:3]

3    b
5    c
dtype: object

In [ ]:
# the loc attribute allows indexing and slicing that always references the explicit index
data.loc[1]

'a'

In [ ]:
data.loc[1:3]

1    a
3    b
dtype: object

In [ ]:
data.loc[1:5]

1    a
3    b
5    c
dtype: object

In [ ]:
# The iloc attribute allows indexing and slicing that always references the implicit Python-style index:

data.iloc[1]

'b'

In [ ]:
data.iloc[1:3]

3    b
5    c
dtype: object

2. Data Selection in DataFrame

In [ ]:
area = pd.Series({'California': 423967, 'Texas': 695662,
'New York': 141297, 'Florida': 170312,
'Illinois': 149995})

pop = pd.Series({'California': 38332521, 'Texas': 26448193,
'New York': 19651127, 'Florida': 19552860,
'Illinois': 12882135})

data = pd.DataFrame({
    'area':area,
    'pop':pop
})

data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [ ]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [ ]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [ ]:
data.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [ ]:
data.area is data['area']

True

Though this is a useful shorthand, keep in mind that it does not work for all cases!
For example, if the column names are not strings, or if the column names conflict
with methods of the DataFrame, this attribute-style access is not possible. For example,
the DataFrame has a pop() method, so data.pop will point to this rather than the
"pop" column:

In [ ]:
data.pop

<bound method DataFrame.pop of               area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135>

In [ ]:
data.pop is data['pop']

False

3. DataFrame as two-dimensional array

In [ ]:
data.values

array([[  423967, 38332521],
       [  695662, 26448193],
       [  141297, 19651127],
       [  170312, 19552860],
       [  149995, 12882135]])

In [ ]:
# With this picture in mind, we can do many familiar array-like observations on the DataFrame itself. For example, we can transpose the full DataFrame to swap rows and columns:

T = data.T
T

California     Texas  New York   Florida  Illinois
area      423967    695662    141297    170312    149995
pop     38332521  26448193  19651127  19552860  12882135

In [ ]:
data.iloc[:3,:1]

area
California  423967
Texas       695662
New York    141297

In [ ]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [ ]:
data.ix[:3,:'pop'] # Deprecated

AttributeError: 'DataFrame' object has no attribute 'ix'

In [ ]:
data.loc[data.area > 150000, ['pop']]

pop
California  38332521
Texas       26448193
Florida     19552860

4. Additional indexing conventions

There are a couple extra indexing conventions that might seem at odds with the preceding
discussion, but nevertheless can be very useful in practice. First, while indexing
refers to columns, slicing refers to rows:

In [ ]:
data['Florida':'Illinois']

area       pop
Florida   170312  19552860
Illinois  149995  12882135

In [ ]:
# Such slices can also refer to rows by number rather than by index:
data[1:3]

area       pop
Texas     695662  26448193
New York  141297  19651127

In [ ]:
# Similarly, direct masking operations are also interpreted row-wise rather than column-wise:
data[data.area > 150000]

area       pop
California  423967  38332521
Texas       695662  26448193
Florida     170312  19552860